config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # resources :courses 
  resources :courses do 
  	collection do 
      	get :enroll, :unenroll, :deleteAll
        post :enroll, :unenroll, :deleteAll
  	end
  end

  get 'home/listMy'
  get 'home/about'
  get 'home/enrolledList'
  root 'courses#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	belongs_to :user
	has_many :records
	has_many :people, through: :records
end

app/models/person.rb
class Person < ApplicationRecord
	belongs_to :user
	has_many :records
	has_many :courses, through: :records
end

app/models/record.rb
class Record < ApplicationRecord
	# belongs_to :person
	# belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :courses
  # belongs_to :person
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  def enroll
    courseid = params[:courseid]
    @person = Person.find_by(user_id: current_user.id)
    Record.create(user_id: @person.id, course_id: courseid)
    redirect_to :root
  end

  def unenroll
    courseid = params[:courseid]
    @person = Person.find_by(user_id: current_user.id)
    Record.destroy_by(user_id: @person.id, course_id: courseid)
    redirect_to :root
  end

  def deleteAll
    user = params[:user]
    Records.delete_by(user_id: People.find_by(user_id: user.id).id)
    People.delete_by(user_id: user.id)
    Courses.delete_by(user_id: user.id)
  end

  # GET /courses/1 or /courses/1.json
  def show
    if !current_user.nil?
      @person = Person.find_by(user_id: current_user.id)
    end
  end

  # GET /courses/new
  def new
    # @course = Course.new
    @course = current_user.courses.build
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    # @course = Course.new(course_params)
    @course = current_user.courses.build(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @course = current_user.courses.find_by(id: params[:id])
    redirect_to courses_path, notice: "Not Authorized to Edit This Friend!" if @course.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:course_name, :course_description, :difficulty, :time_required, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def listMy
  	@courses = Course.all
  end

  def enrolledList
  	@records = Record.all
  	@mycourses = []
  	@records.each do |record|
  		if Person.find(record.user_id).user_id == current_user.id
  			@mycourses.push(Course.find(record.course_id));
  		end
  	end
  end
  
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-floating mb-3">
    <%= form.text_field :course_name, class:"form-control", id:"floatingName", placeholder:"Course Name" %>
    <%= form.label :course_name, for:"floatingName" %>
  </div>

  <div class="field form-floating mb-3">
    <%= form.text_field :course_description, class:"form-control", id:"floatingDescription", placeholder:"Description" %>
    <%= form.label :course_description, for:"floatingDescription" %>
  </div>

  <div class="field form-floating mb-3">
    <%= form.text_field :difficulty, class:"form-control", id:"floatingDifficulty", placeholder:"Difficulty" %>
    <%= form.label :difficulty, for:"floatingDifficulty" %>
  </div>

  <div class="field form-floating mb-3">
    <%= form.text_field :time_required, class:"form-control", id:"floatingTimeRequired", placeholder:"Time Required" %>
    <%= form.label :time_required, for:"floatingTimeRequired" %>
  </div>

  <div class="field">
    <%= form.number_field :user_id, id: :course_user_id, value:current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-dark" %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>
<br>
<%= render 'form', course: @course %>
<br>
<%= link_to 'Show', @course, class:"btn btn-secondary" %>
<%= link_to 'Delete', @course, method: :delete, data: {confirm: 'Are you sure?'}, class:"btn btn-danger btn" %>

app/views/courses/index.html.erb
<h1>Courses</h1>

<% if !current_user.nil? %>
  <% if Person.find_by(user_id: current_user.id).nil? %>
    <% Person.create(user_id: current_user.id) %>
  <% end %>
<% end %>

<table class="table table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Course name</th>
      <th>Description</th>
      <th>Difficulty</th>
      <th>Time required</th>
      <th>Developed by</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.course_name %></td>
        <td><%= course.course_description %></td>
        <td><%= course.difficulty %></td>
        <td><%= course.time_required %></td>
        <td><%= User.find(course.user_id).email %></td>
        <td><%= link_to 'Show', course, class:"btn btn-outline-secondary btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/courses/new.html.erb
<h1>Create New Course</h1>

<%= render 'form', course: @course %>

<br>
<%= link_to 'Back', courses_path, class:"btn btn-secondary" %>

app/views/courses/show.html.erb
<div class="p-3 mb-2 bg-light text-dark">
  <h1 class="display-4"><%= @course.course_name %></h1>
  <p class="lead">
  	<strong>Difficulty:</strong> <%= @course.difficulty %>;<br>
  	<strong>Time required:</strong> <%= @course.time_required %>;<br>
  	<strong>Description:</strong> <%= @course.course_description %> </p>
  <hr class="my-4">
  <p>
  	<!-- FULL COURSE DESCRIPTION -->
  </p>

  <br>
  <% if @course.user == current_user %>
    <%= link_to 'Edit', edit_course_path(@course), class:"btn btn-dark" %>
  <% else %>
    <% if !current_user.nil? %>
      <% if Record.find_by(user_id: @person.id, course_id: @course.id).nil? %>
        <%= link_to 'Enroll', enroll_courses_path(courseid: @course.id), class:"btn btn-success" %>
      <% else %>
        <%= link_to 'Unenroll', unenroll_courses_path(courseid: @course.id), class:"btn btn-warning" %>
      <% end %>
    <% end %>
  <% end %>


</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'E-Learning', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        

        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Courses
            </a>

            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                <%= link_to "All Courses", courses_path, class:"dropdown-item" %>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= link_to "Enrolled Courses", home_enrolledList_path, class:"dropdown-item" %>
              </li>
            </ul>

          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              My Courses
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                <%= link_to "Created Courses", home_listMy_path, class:"dropdown-item" %>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= link_to "Create Course", new_course_path, class:"dropdown-item" %>
              </li>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Profile
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                <%= link_to "Edit Profile", edit_user_registration_path, class:"dropdown-item" %>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
              </li>
            </ul>
          </li>
        <% else %>

          <li class="nav-item">
            <%= link_to "Courses", courses_path, class:"nav-link" %>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Authorization
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                <%= link_to "Sign up", new_user_registration_path, class:"dropdown-item" %>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= link_to "Sign in", new_user_session_path, class:"dropdown-item" %>
              </li>
            </ul>
          </li>
        <% end %>

          

        <li class="nav-item">
          <%= link_to "About Us", home_about_path, class:"nav-link" %>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>

app/views/home/enrolledList.html.erb
<h1>Enrolled Courses</h1>

<table class="table table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Course name</th>
      <th>Description</th>
      <th>Difficulty</th>
      <th>Time required</th>
      <th>Developed by</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @mycourses.each do |course| %>
      <tr>
        <td><%= course.course_name %></td>
        <td><%= course.course_description %></td>
        <td><%= course.difficulty %></td>
        <td><%= course.time_required %></td>
        <td><%= User.find(course.user_id).email %></td>
        <td><%= link_to 'Show', course, class:"btn btn-outline-secondary btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/listMy.html.erb
<h1>My Courses</h1>

<table class="table table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Course name</th>
      <th>Description</th>
      <th>Difficulty</th>
      <th>Time required</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <% if course.user == current_user %>
        <tr>
          <td><%= course.course_name %></td>
          <td><%= course.course_description %></td>
          <td><%= course.difficulty %></td>
          <td><%= course.time_required %></td>
          <td><%= link_to 'Show', course, class:"btn btn-outline-secondary btn-sm" %></td>
          <td><%= link_to 'Edit', edit_course_path(course), class:"btn btn-outline-dark btn-sm" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Course', new_course_path, class:"btn btn-dark" %>  

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>E-Learning!</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <br>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>